ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui
content:
  sources: []
site:
  title: Teragrep Docs
  url: https://docs.teragrep.com
antora:
  extensions:
  - '@antora/collector-extension'
