name: Create docs
on: [ push ]

jobs:
  create_docs:
    name: Create docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Cache Local Maven Repository
      uses: actions/cache@v5
      with:
        path: ~/.m2/repository
        key: always-m2

    - name: Cache synced repositories
      uses: actions/cache@v5
      with:
        path: ${{ runner.temp }}/repos
        key: always-repos

    - name: Clone repositories
      run: |
        set -e;
        set -x;
        echo '{}' > "${{ runner.temp }}/tags.json";
        for repo in buf_01 pth_03; do
          gh repo clone "StrongestNumber9/${repo}" "${{ runner.temp }}/repos/${repo}" --no-upstream;
          (
            cd "${{ runner.temp }}/repos/${repo}";
            for tag in $(git tag); do
              if [ -n "$(git ls-tree "$tag" -- antora.yml)" ]; then
                echo "$tag";
              fi
            done;
          ) | jq --raw-input --arg repo "${repo}" '$repo=(inputs|split(" "))' "${{ runner.temp }}/tags.json" > "${{ runner.temp }}/tags.json.tmp";
          mv -f -v "${{ runner.temp }}/tags.json.tmp" "${{ runner.temp }}/tags.json";
        done;
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Debug
      run: |
        find ~/.m2/;
        find "${{ runner.temp }}/repos/";
