name: Create docs
on: [ push ]

jobs:
  create_docs:
    name: Create docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Cache synced repositories
      uses: actions/cache@v5
      with:
        path: ${{ runner.temp }}/repos
        key: always-repos

    - name: Cache Local Maven Repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: always-m2

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Install Antora
      run: |
        npm i -g @antora/cli@ @antora/site-generator @antora/collector-extension

    - name: Clone repositories and create playbook
      run: |
        set -e;
        mkdir -p "${{ runner.temp }}/tags/";
        for repo in buf_01 pth_06; do
          if [ ! -d "${{ runner.temp }}/repos/${repo}" ]; then
            gh repo clone "StrongestNumber9/${repo}" "${{ runner.temp }}/repos/${repo}" --no-upstream;
          fi;
          (
            cd "${{ runner.temp }}/repos/${repo}";
            gh repo sync;
            git tag | while read -r tag; do
              if [ -n "$(git ls-tree --name-only "${tag}" antora.yml)" ]; then
                echo "${tag}";
              fi;
            done | jq -R . | jq -s . > "${{ runner.temp }}/tags/${repo}.json";
          )
        done;
        python create_antora_playbook.py > antora-playbook.yml;
        cat antora-playbook.yml;
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Generate docs
      run: |
        antora antora-playbook.yml --stacktrace;

    - name: Attach artifact to the build
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: build
